  
version: '3'
services:
  spark-batch:
    depends_on:
      - web
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./:/code/
    links:
    - "db:database"
    environment:
      MASTER: local
      MONGODB_URL: mongodb://username:password@database:27017
      MONGODB_DATABASE: experiments
    command: >
      bash -c "sbt local/reStart && tail -F anything"
  web:
    depends_on:
      - db
    build:
      context: ../app
      dockerfile: Dockerfile.dev
    ports:
    - '80:3000'
    volumes:
    - /code/node_modules
    links:
    - "db:database"
    environment:
      MONGODB_URL: mongodb://username:password@database:27017
      MONGODB_DATABASE: experiments
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
