FROM amazonlinux

RUN yum install -y java-1.8.0-openjdk-devel
RUN yum install -y https://dl.bintray.com/sbt/rpm/sbt-1.3.8.rpm
RUN yum install -y wget
RUN yum install -y tar

ADD http://www-eu.apache.org/dist/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz .
RUN tar -xzf spark-2.4.5-bin-hadoop2.7.tgz 
RUN sbt update

COPY . code
WORKDIR /code
