version: '3'
services:
  user-activity-web:
    command: >
      bash -c "npm start -- \
        --randomDataDump \
        --projects 5e865ed82a2aeb6436f498dc,5e865ed82a2aeb6436f498de,5e865ed82a2aeb6436f498d7,5e865ed82a2aeb6436f498dd \
        --segments one,two,three,four \
        --userActions buy,click,view \
        --userVolume 50 --sessionVolume 200 --activityVolume 1000 \
        --minTimestamp 79839129600000 --maxTimestamp 79839302400000"
      
