  
version: '3'
services:
  user-activity-web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - '80:80'
    volumes:
    - ./:/code/
    - /code/node_modules
    links:
    - "db:database"
    - "experiments-web:experiments-web"
    environment:
      MONGODB_URL: mongodb://username:password@database:27017
      MONGODB_DATABASE: user_activity
      PUBLIC_EXPERIMENTS_SERVICE_HOST: experiments-web
      PUBLIC_EXPERIMENTS_SERVICE_PORT: 80
  experiments-web:
    depends_on:
      - db
    image: gcr.io/grizzly-bear-271511/grizzly-bear-prod/experiments:latest
    ports:
    - '3000:80' # Public API
    - '8080:8080' # Private API
    volumes:
    - /code/node_modules
    links:
    - "db:database"
    environment:
      MONGODB_URL: mongodb://username:password@database:27017
      MONGODB_DATABASE: experiments
      AUTH_SIGN_KEY_URI: https://grizzly-bear-dev.eu.auth0.com/.well-known/jwks.json
      AUTH_AUDIENCE: http://www.grizzlybear-experiments.com
      AUTH_DOMAIN: https://grizzly-bear-dev.eu.auth0.com/
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
