apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: experimentStats
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: experimentStats
            image: BATCH_DOCKER_IMAGE
          restartPolicy: OnFailure