apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: experiment-stats
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: experiment-stats
            image: BATCH_DOCKER_IMAGE
          restartPolicy: OnFailure