apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: experiment-stats
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: experiment-stats
            image: BATCH_DOCKER_IMAGE
            imagePullPolicy: IfNotPresent
            env:
              - name: MONGODB_URL
                valueFrom:
                  secretKeyRef:
                    name: user-activity-db-secret
                    key: MONGODB_URL
              - name: MONGODB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: user-activity-db-secret
                    key: MONGODB_DATABASE
              - name: MASTER
                valueFrom:
                  configMapKeyRef:
                    name: user-activity-config-map
                    key: SPARK_CLUSTER_MASTER
          restartPolicy: OnFailure
