apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: BATCH_DOCKER_IMAGE
  newName: user-activity-batch
  newTag: dev
- name: WEB_DOCKER_IMAGE
  newName: user-activity-web
  newTag: dev
