name: Deploy To GKE

on: 
    deployment

env:
    GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
    GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
    GKE_KEY: ${{secrets.GKE_KEY}}
    GITHUB_SHA: ${{ github.sha }}
    GKE_ZONE: ${{ github.event.deployment.payload.gke_zone }}
    GKE_CLUSTER: ${{ github.event.deployment.payload.gke_cluster }}
    ENVIRONMENT: ${{ github.event.deployment.payload.environment }}
    DEPLOYMENT_NAME: user-activity-deployment
    IMAGE: user-activity
    REGISTRY_HOSTNAME: gcr.io

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # Setup gcloud CLI
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: "270.0.0"
                  service_account_email: ${{ env.GKE_EMAIL }}
                  service_account_key: ${{ env.GKE_KEY }}

            # Configure docker to use the gcloud command-line tool as a credential helper
            - run: |
                  # Set up docker to authenticate
                  # via gcloud command-line tool.
                  gcloud auth configure-docker

            # Build the Docker image
            - name: Build
              run: |
                  docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$GKE_CLUSTER"/"$IMAGE":"$GITHUB_SHA" \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" .

            # Push the Docker image to Google Container Registry
            - name: Publish
              run: |
                  docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/"$GKE_CLUSTER"/$IMAGE:$GITHUB_SHA
            
            # Deploy the Docker image to the GKE cluster
            - name: Deploy
              run: |
                gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
                cd kubernetes/overlays/$ENVIRONMENT
                curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
                chmod u+x ./kustomize
                ./kustomize edit set image XXXX=$REGISTRY_HOSTNAME/$GKE_PROJECT/"$GKE_CLUSTER"/$IMAGE:${GITHUB_SHA}
                ./kustomize build . | kubectl apply -f -
                kubectl rollout status deployment/$DEPLOYMENT_NAME
                kubectl get services -o wide