# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: public_docker_image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: ./.github/workflows/test.yml
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: nj20/grizzly_bear-user_activity/user_activity
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        registry: docker.pkg.github.com

