name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-dir: ./app
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: ${{env.node-dir}}
    - run: npm test && npm run test:acceptance
      working-directory: ${{env.node-dir}}
