name: test

on:
  deployment

env:
  EVENT: ${{ github.event }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      node-dir: ./app
    steps:
    - name: Testing
      run: echo $EVENT
      working-directory: ${{env.EVENT}}
