name: Test

on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            node-dir: ./app
        steps:
            # Setting up repo with node
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            # Running tests
            - name: Testing
              run: npm install && npm test
              working-directory: ${{env.node-dir}}
